#!/usr/bin/bash

# Prepare build opts
GCC_OPTS="-Wno-overflow -fwrapv -Wno-narrowing"
if [ "$OSTYPE" = "msys" ]; then
	if ! cmake --version >/dev/null; then scoop install cmake; fi
	if ! upx -V >/dev/null; then scoop install upx; fi
	if ! g++ -v 2>/dev/null; then scoop install mingw; fi
	winmf='-G "MinGW Makefiles"'
	SDL_STATIC_LINK_FLAGS="-L.bin/lib -lmingw32 -lSDL2 -lSDL2main -Wl,--dynamicbase -Wl,--nxcompat -Wl,--high-entropy-va -lm -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lsetupapi -lversion -luuid -static -Dmain=SDL_main"
else
	lxdeps="sudo apt-get install libasound2-dev libpulse-dev cmake upx"
	SDL_STATIC_LINK_FLAGS="-L.bin/lib -lSDL2 -lSDL2main -ldl -pthread"
fi

# Say NO to windows build system
if [ ! -d .bin ]; then
rm -rf .bin2
mkdir .bin2
git clone https://github.com/BlobTheKat/glad-everywhere --depth=1
mv glad-everywhere/include .bin2
mv glad-everywhere/src .bin2
rm -rf glad-everywhere
git clone -b SDL2 https://github.com/libsdl-org/SDL --depth=1
$lxdeps
cmake $winmf -S SDL -B SDL/build -DCMAKE_BUILD_TYPE=Release -DSDL_STATIC=ON -DSDL_SHARED=OFF -DSDL_DYNAMIC_API=OFF -DSDL_RENDER_DISABLED=ON -DSDL_RENDER_D3D=OFF -DSDL_RENDER_METAL=OFF -DSDL_VULKAN=OFF -DSDL_TEST=OFF && cmake --build SDL/build --config Release --parallel || exit
mv SDL/include .bin2/include/SDL2
mkdir .bin2/lib
mv SDL/build/*.a .bin2/lib
rm -rf SDL
mv .bin2 .bin
fi

# Build
clear
A=
for arg in "$@"; do
A="$A -D$arg"
declare "ARG_$arg$(expr "$arg" : ".*=.*" >/dev/null || echo "=")"
done
postbuild(){
	./main $A
}
if [ "${ARG_RELEASE+x}" ]; then
GCC_OPTS="$GCC_OPTS -O3"
postbuild(){
	upx --best main
}
if [ "$winmf" ]; then
if [ ! -f icon.ico ]; then
echo -e "\033[mWarning: no icon.ico found. Building without an icon...\033[m"
else
echo "id ICON icon.ico" > .rc
windres .rc -O coff -o .icon.res
rm .rc
fi;
GCC_OPTS="$GCC_OPTS .icon.res -mwindows"
postbuild(){
	rm .icon.res
	upx.exe --best main.exe
}
fi; fi

clang++ -fno-rtti -flto -I.bin/include -Wfatal-errors -std=c++20 $GCC_OPTS $A src/main.cpp .bin/src/gl.c -Wl,--strip-all -ffunction-sections $SDL_STATIC_LINK_FLAGS -Wl,--gc-sections -Wl,--format=binary -Wl,$(find assets/*) -Wl,--format=default -o main && postbuild