#!/usr/bin/sh

# Prepare build opts
GCC_OPTS="-Wno-overflow -fwrapv -Wno-narrowing"
if [ "$OSTYPE" = "msys" ]; then
	if ! cmake --version 2>&1 /dev/null; then scoop install cmake; fi
	if ! g++ -v 2>/dev/null; then scoop install mingw; fi
	SDL_STATIC_LINK_FLAGS="-L.bin/lib -lmingw32 -lSDL2 -lSDL2main -Wl,--dynamicbase -Wl,--nxcompat -Wl,--high-entropy-va -lm -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lsetupapi -lversion -luuid -static -Dmain=SDL_main"
	if [ ! -f icon.ico ]; then
	echo -e "\033[mWarning: no icon.ico found. Building without an icon...\033[m"
	else
	echo "id ICON icon.ico" > .rc
	windres .rc -O coff -o .icon.res
	rm .rc
	GCC_OPTS=".icon.res $GCC_OPTS"
	fi
	if [ "$1" ]; then GCC_OPTS="$GCC_OPTS -O3 -mwindows -DRELEASE=$1"; fi
	winmf='-G "MinGW Makefiles"';
else
	lxdeps="sudo apt-get install libasound2-dev libpulse-dev"
	SDL_STATIC_LINK_FLAGS="-L.bin/lib -lSDL2 -lSDL2main -ldl -pthread"
	if [ "$1" ]; then GCC_OPTS="$GCC_OPTS -O3 -DRELEASE=$1"; fi;
fi

# Say NO to windows build system
if [ ! -d .bin ]; then
rm -rf .bin2
mkdir .bin2
git clone https://github.com/BlobTheKat/glad-everywhere
mv glad-everywhere/include .bin2
mv glad-everywhere/src .bin2
rm -rf glad-everywhere
git clone -b SDL2 https://github.com/libsdl-org/SDL
$lxdeps
cmake $winmf -S SDL -B SDL/build -DCMAKE_BUILD_TYPE=Release -DSDL_STATIC=ON -DSDL_DYNAMIC=OFF
cmake --build SDL/build --config Release --parallel
mv SDL/include .bin2/include/SDL2
mkdir .bin2/lib
mv SDL/build/*.a .bin2/lib
rm -rf SDL
mv .bin2 .bin
fi

# Build
clear
g++ -I.bin/include -Wfatal-errors -std=c++20 -O3 src/main.cpp .bin/src/gl.c -Wl,--strip-all -ffunction-sections $GCC_OPTS $SDL_STATIC_LINK_FLAGS -Wl,--gc-sections -Wl,--format=binary -Wl,assets/basic.frag -Wl,assets/basic.vert -Wl,--format=default -o main
A=$?

if [ -f .icon.res ]; then rm .icon.res; fi

# Run executable after a successful build
if [ $A -eq 0 ]; then
echo -e "\033[32mBuild successful. Enter argv and hit enter to run\033[m"
read A; clear
./main $A
fi